language: node_js
node_js:
  - 12

install:
  - npm install

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:

- node_modules/.bin/newman run https://github.com/PSTPAGOFACIL/APIs_Automatizacion/blob/qa/API%20Blacklist.postman_collection.json -e
