language: node_js
node_js:
  - 12
  
install:
- npm init
- npm install --save newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:

- node_modules/.bin/newman run APIs_Automatizacion/API_Blacklist.postman_collection.json
