language: node_js
node_js:
  - 12

install:
  - npm install

before_script:
- node --version
- npm --version

script:

- node_modules/.bin/newman run APIs_Automatizacion/API_Blacklist.postman_collection.json -e
