language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:

- node_modules/.bin/newman run tests/API Blacklist.postman_collection.json
