language: node_js
node_js:
  - 12
  
install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:

- node_modules/.bin/newman run AlexCabrera23/APIs_Automatizacion/API_Blacklist.postman_collection.json
#- node_modules/.bin/newman run APIs_Automatizacion/API nullification - Anular transacciones.postman_collection.json
